### ISSUE TITLE
indent-hint.el makes my emacs slow

### ISSUE THREAD

**Issue by rhoit** [ran9er/init.emacs#2]
I recently ditched the https://github.com/antonj/Highlight-Indentation-for-Emacs for indent-hint.el. I really loved the way it show the indentation, but it is too slow when I tried with _python_ or something I did is wrong. 

I added `(load "~/.emacs.d/indent-hint.el")` to my .emacs file
and start it using `M-x indent-hint-mode`

P.S. I'm not good with elisp

**Comment by ran9er** [comment]
There are two main reasons:
1) This addon draw indent hint when emacs render syntax highlight , and 
emacs render syntax in a high freqency .
2) When emacs refresh indent hint , it will generate a lot of overlay , 
GC couldn't collect those overlay immediately .

To solve this problem, We will find a new mechanism to render indent 
hint , or implement a efficient GC.

If only use it for python , the things is sample, because the indent of 
python is fixed.

P.S. I'm not good with english
在 2014年07月05日 13:24, rho 写道:

> I recently ditched the 
> https://github.com/antonj/Highlight-Indentation-for-Emacs for 
> indent-hint.el. I really loved the way it show the indentation, but it 
> is too slow or something I did is wrong.
> 
> I added |(load "~/.emacs.d/indent-hint.el")| to my .emacs file
> and start it using |M-x indent-hint-mode|
> I'm using it for python.
> 
> P.S. I'm not good with elisp
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ran9er/init.emacs/issues/2.

## 

﻿λƒ.(λχ.(ƒ(χ χ))λχ.(ƒ(χ χ)))

**Comment by rhoit** [comment]
I recently updated the emacs, and jedi (Python auto-completion for Emacs), its not slow now, but its broken, even in fundamental mode. here are the screenshot.

normal python mode.
![screenshot9](https://cloud.githubusercontent.com/assets/1684754/3692912/58a7f820-1361-11e4-8c8f-841267aa7441.png)

in fundamental mode with indent-hint
![screenshot6](https://cloud.githubusercontent.com/assets/1684754/3692865/d5dc0f26-1360-11e4-8287-a4f2ee307b72.png)

with python-mode
![screenshot7](https://cloud.githubusercontent.com/assets/1684754/3692874/f70dfd94-1360-11e4-8fce-67aed087120d.png)

both highlight-indentation 
![screenshot8](https://cloud.githubusercontent.com/assets/1684754/3692891/19e22ef8-1361-11e4-9118-f915a7fc8b8f.png)

**Comment by ran9er** [comment]
broken because this program suppose that  there is not blank line in a 
block of code .
this is the logic for draw indent hint line, you can modify it

(defun draw-indent-hint-line (&optional column img color)
   (interactive "P")
   (save-excursion
     (let\* ((i (or column (current-indentation)))
            (h (ih-make-head))
            (m (progn (forward-line)
                      (move-to-column i)
                      (ih-count-line)))
            (x (car m))(y (cdr m)) lst)
       (if (> x 0)
           (progn
             (kill-indent-hint (point))
             (dotimes (n x)
               (if (memq n y)
                   (ihwl-insert i h img color)
                 (setq lst (cons (draw-indent-hint (point) h img color) 
lst)))
               (forward-line)
               (move-to-column i))
             (ih-put h (cons y lst)))))))

this is  the interface for rendering syntax, you can write your addon to 
display indent hint. (with python (pymacs))

(defun indent-hint (&optional regexp column img color)
   (interactive)
   (let ((x (or regexp "^")))
     (font-lock-add-keywords
      nil `((,x
             (0 (draw-indent-hint-line ,column ,img ,color)))))))

在 2014年07月25日 02:36, rho 写道:

> I recently updated the emacs, and jedi (Python auto-completion for 
> Emacs), its not slow now, but its broken, even in fundamental mode. 
> here are the screenshot.
> 
> normal python mode.
> screenshot9 
> https://cloud.githubusercontent.com/assets/1684754/3692912/58a7f820-1361-11e4-8c8f-841267aa7441.png
> 
> in fundamental mode with indent-hint
> screenshot6 
> https://cloud.githubusercontent.com/assets/1684754/3692865/d5dc0f26-1360-11e4-8287-a4f2ee307b72.png
> 
> with python-mode
> screenshot7 
> https://cloud.githubusercontent.com/assets/1684754/3692874/f70dfd94-1360-11e4-8fce-67aed087120d.png
> 
> both highlight-indentation
> screenshot8 
> https://cloud.githubusercontent.com/assets/1684754/3692891/19e22ef8-1361-11e4-9118-f915a7fc8b8f.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ran9er/init.emacs/issues/2#issuecomment-50059246.

## 

﻿λƒ.(λχ.(ƒ(χ χ))λχ.(ƒ(χ χ)))
